### PR TITLE
Update to edition 2018 and compile with recent rust versions

### PR DESCRIPTION
**Pull request by zayenz**
This commit contains a lot of small changes to update fall to edition
2018, mostly adding lots of dyn to dynamic object references and
updating imports.

Tera is updated to a recent version since older version of tera used a
version of the url crate that did not compile anymore.

An update to the fst crate made the fst::Map generic. The previous
implicit Vec<u8> is used as the argument now.

The generated tests are updated to also be valid rust 2018.

Test output ocmparisons are now done trimming the ends of lines, in
order to work when using a CLion that insists on stripping trailing
whitespace.

The last change (trimming ends of lines) is the only potentially 
controversial change as far as I can see it, since the comparison 
is no longer strict.

### CODE REVIEW

**Comment by ckaran** [comment]
> Test output ocmparisons are now done trimming the ends of lines, in
order to work when using a CLion that insists on stripping trailing
whitespace.

> The last change (trimming ends of lines) is the only potentially
controversial change as far as I can see it, since the comparison
is no longer strict.

Just so I'm 100% clear, this only affects the tests, correct?  The parsed tree still contains that information, correct?

**Comment by zayenz** [comment]
> Just so I'm 100% clear, this only affects the tests, correct? The parsed tree still contains that information, correct?

This is purely for the snapshot testing of the generated parsers, so it has nothing to do with the actual output and how it works.

Shortly, the issue is that some editors (such as CLion) aggressively trims whitespace at end of lines. ost of the times, this is a nice feature, but when done to files that are intended to be byte for byte compared against generated output, this is not what is wanted.

This change will allow slightly more variation in the output, but it is only differences in whitespace at end of lines and empty lines in the generated parser code.

**Comment by ckaran** [comment]
@zayenz Got it, thank you for the clarification.

**Comment by matklad** [comment]
:+1:

**Pull request merged**
